### PR TITLE
[TRAN-206] Adding barcode to label class

### PR DESCRIPTION
**Pull request by andrewpaek**
JIRA: https://jira.blueapron.com/browse/TRAN-206 

Tested locally

### CODE REVIEW

**Comment by KevinBongart** [comment]
Why close this?

**Comment by venky91** [comment]
You should probably remove me from this project. 😊

**Comment by Parad0X** [comment]
We have access to the entire fedex api response. We don't need to modify the api client.

**Comment by KevinBongart** [comment]
@venky91 It's a public project! You should be able to unfollow it though

**Comment by venky91** [comment]
@KevinBongart :heart:

**Pull request closed without merging**
